foo: this is default bar from cloudclient.yml
---
spring:
    profiles: cloudprofile
foo: thisis bar cloudiprofile after refreshed 2:18pm

---
spring:
    profiles: localprofile
food: this is foobar from localprofile
