hinfoo: hinbar
spring:
    profiles: configserver
    server:
        prefix: /hinconfig
            git:
                uri: https://github.com/hinyinlam/springcloudconfig-demo

---
spring:
   profiles: configserver2
hinfoo: hinbar2
